# Generated by Django 5.2.14 on 2026-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['slug'], name='academics_s_slug_09ecf7_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['slug'], name='academics_s_slug_31a087_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester'], name='academics_s_semeste_028522_idx'),
        ),
    ]
