# Generated by Django 5.2.14 on 2026-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_semester_academics_s_slug_09ecf7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='past_questions',
            field=models.JSONField(blank=True, default=dict, help_text='Past year questions grouped by year', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.JSONField(blank=True, default=dict, help_text='Syllabus structure with units and topics', null=True),
        ),
    ]
