# Generated by Django 5.2.14 on 2026-06-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_past_questions_subject_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short summary shown on chapter cards.')),
                ('lecture_hours', models.PositiveSmallIntegerField(default=0, help_text='Official lecture hours from TU syllabus.')),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.subject')),
            ],
            options={
                'ordering': ['display_order', 'unit_number'],
                'indexes': [models.Index(fields=['subject'], name='academics_s_subject_973c0a_idx'), models.Index(fields=['display_order'], name='academics_s_display_44615c_idx')],
                'unique_together': {('subject', 'unit_number')},
            },
        ),
    ]
