# Generated by Django 5.2.14 on 2026-06-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('notes', 'Notes'), ('syllabus', 'Syllabus'), ('past_questions', 'Past Questions'), ('model_questions', 'Model Questions'), ('important', 'Important')], max_length=50)),
                ('file', models.FileField(upload_to='resources/pdfs/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.subject')),
            ],
        ),
    ]
