# Generated by Django 5.2.14 on 2026-06-09 08:41

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_file_size_alter_resource_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(storage=config.storage.PrivateMediaStorage(), upload_to='resources/pdfs/'),
        ),
    ]
