# Generated by Django 5.2.14 on 2026-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='allow_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, help_text='Used for custom ordering of resources. ', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='question_year',
            field=models.PositiveIntegerField(blank=True, help_text='Used for past questions to indicate the year. ', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='unit_number',
            field=models.PositiveIntegerField(blank=True, help_text='Used for ordering resources within a subject.', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='viewer_type',
            field=models.CharField(choices=[('inline', 'Inline Viewer'), ('download', 'Download Only')], default='inline', max_length=50),
        ),
    ]
