# Generated by Django 5.2.14 on 2026-06-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_subject_past_questions_subject_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('full_marks', models.PositiveIntegerField(default=100)),
                ('pass_marks', models.PositiveIntegerField(default=40)),
                ('duration', models.CharField(default='3 Hours', max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='academics.subject')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], max_length=10)),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_bank.pastpaper')),
            ],
            options={
                'ordering': ['section', 'display_order', 'question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['subject'], name='question_ba_subject_dfa9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['year'], name='question_ba_year_bcdebe_idx'),
        ),
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['is_published'], name='question_ba_is_publ_d318c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pastpaper',
            unique_together={('subject', 'year')},
        ),
        migrations.AddIndex(
            model_name='pastquestion',
            index=models.Index(fields=['paper'], name='question_ba_paper_i_284f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='pastquestion',
            index=models.Index(fields=['section'], name='question_ba_section_7cf858_idx'),
        ),
    ]
